changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: SOME FIXES
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"