name: Push a new tag and create release

on:
  workflow_dispatch

jobs:
  bump-version-and-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # required by PaulHatch/semantic-version
          fetch-depth: 0

      - name: Git Semantic Version
        id: semantic
        uses: PaulHatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(major)"
          # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          major_regexp_flags: ""
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(minor)"
          bump_each_commit: true
          search_commit_body: true

      - name: Print current release version to console
        run: echo Current Release Version is ${{ github.event.release.tag_name }}

      - name: actor
        run: |
          echo "The job_id is: $GITHUB_JOB"   
          echo "The id of this action is: $GITHUB_ACTION"
          echo "The run id is: $GITHUB_RUN_ID" 
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"

      - name: Tag
        run: |
          echo " SEMVER is ${{ steps.semantic.outputs.version  }}"
          tag=${{ steps.semantic.outputs.version  }}
          message='${{ steps.semantic.outputs.version }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@gmail.com"
          git tag -a "v${tag}" -m "${message}"
          git push origin "v${tag}"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "categories": [
                  {
                    "title": "## 🚀 Features",
                    "labels": ["feature"]
                  },
                  {
                    "title": "## 🐛 Bugfixes",
                    "labels": ["bugfix"]
                  },
                  {
                    "title": "## 🪄 Enhancements",
                    "labels": ["enhancement"]
                  },
                  {
                    "title": "## 🧪 Tests,
                    "labels": ["test"],
                    "exhaustive": true,
                    "exhaustive_rules": "false",
                    "empty_content": "- no matching PRs",
                    "rules": [
                      {
                        "pattern": "open",
                        "on_property": "status",
                        "flags": "gu"
                      }
                    ]
                  }
              ],
                "ignore_labels": [
                  "ignore"
                ],
                "sort": {
                  "order": "ASC",
                  "on_property": "mergedAt"
                }
            }

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          generateReleaseNotes: true
          tag: ${{ steps.semantic.outputs.version }}
          body: ${{ steps.github_release.outputs.changelog }}
