name: Push a new tag and create release

on:
  # workflow_dispatch
  push:
    branches:
      - main

jobs:
  bump-version-and-tag-release:
    runs-on: ubuntu-latest
    steps:
      # - name: Print Context
      #  run: echo "${{ toJSON(github) }}"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # required by PaulHatch/semantic-version
          fetch-depth: 0

      - name: Semantic Version
        id: semver
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(major)"
          minor_pattern: "(minor)"
          version_format: "v${major}.${minor}.${patch}"
          search_commit_body: true
          # version_from_branch: true
          # debug: true

#      - name: Print current release version to console
#        run: |
#          echo "Debug: ${{ fromJSON(steps.semver.outputs.debug_output) }}"

#      - name: actor
#        run: |
#          echo "The job_id is: $GITHUB_JOB"
#          echo "The id of this action is: $GITHUB_ACTION"
#          echo "The run id is: $GITHUB_RUN_ID"
#          echo "The GitHub Actor's username is: $GITHUB_ACTOR"

#      - name: Create tag and push
#        run: git tag ${{ steps.semver.outputs.version }} && git push --tags

      - name: Create Tag
        if: success() #if: steps.semver.outcome == 'success'
        run: |
          tag=${{ steps.semver.outputs.version }}
          message='${{ steps.semver.outputs.version }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@gmail.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\nDiff: #{{RELEASE_DIFF}}",
              "pr_template": "- #{{TITLE}} (#{{URL}})", 
              "categories": [
                {
                  "title": "## Bug Fixes",
                  "labels": ["bug", "fix"]
                },
                {
                  "title": "## Enhancements",
                  "labels": ["enhancement"]
                },
                {
                  "title": "## New Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## BREAKING CHANGES",
                  "labels": ["major"]
                },
                {
                  "title": "## Changes",
                  "labels": []
                }
              ]
            }
#      - name: Echo Configuration Build Changelog
#        run: echo "${{ steps.without_checkout.outputs.changelog }}"

      - name: Create Release Note
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.semver.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          removeArtifacts: true
