name: Push a new tag and create release

on:
  workflow_dispatch

jobs:
  bump-version-and-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: semantic
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          major_pattern: "(major)"
          # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          major_regexp_flags: ""
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(minor)"
          bump_each_commit: true
          search_commit_body: true

      - name: Print current release version to console
        run: echo Current Release Version is ${{ github.event.release.tag_name }}

      - name: actor
        run: |
          echo "The job_id is: $GITHUB_JOB"   
          echo "The id of this action is: $GITHUB_ACTION"
          echo "The run id is: $GITHUB_RUN_ID" 
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"

      - name: Tag
        run: |
          echo " SEMVER is ${{ steps.semantic.outputs.version  }}"
#          tag=${{ steps.semantic.outputs.version  }}
#          message='${{ steps.semantic.outputs.version }}: PR '
#          git config user.name "${GITHUB_ACTOR}"
#          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#          git tag -a "${tag}" -m "${message}"
#          git push origin "${tag}"